### ISSUE TITLE
Python 3.7 breaks cocotb because of changes in the logging framework

### ISSUE THREAD

**Issue by G33KatWork** [potentialventures/cocotb#646]
When running cocotb testbenches on Python 3.7 I get the following traceback

```
Traceback (most recent call last):
  File "/run/media/andy/Data/Autocopter/fpga/rectification/cocotb/cocotb/__init__.py", line 68, in <module>
    log.setLevel(_default_log)
  File "/usr/lib/python3.7/logging/__init__.py", line 1308, in setLevel
    self.manager._clear_cache()
  File "/usr/lib/python3.7/logging/__init__.py", line 1267, in _clear_cache
    logger._cache.clear()
AttributeError: 'SimBaseLog' object has no attribute '_cache'
```

It seems that python now tries to clear some cache on a log level change if the logger has `Logger` as a base class. It is not immediately obvious to me how to fix this except adding a dummy `_cache` member and giving it an empty `clear` function.

**Comment by G33KatWork** [comment]
Nevermind. Fixed it: https://github.com/potentialventures/cocotb/pull/647
