### ISSUE TITLE
import simulator failed

### ISSUE THREAD

**Issue by kimduckhwan** [potentialventures/cocotb#794]
Centos release 6.8
Python version 2.7.13

I installed cocotb via pip command
```pip install cocotb```

I have a error for `import cocotb`  such as 
```
>>> import cocotb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/my_env_p2713/lib/python2.7/site-packages/cocotb/__init__.py", line 41, in <module>
    import cocotb.handle
  File "/my_env_p2713/lib/python2.7/site-packages/cocotb/handle.py", line 45, in <module>
    import simulator
ImportError: No module named simulator
```

Do I miss any dependency?

Thank you

**Comment by themperek** [comment]
Install via pip is not yet supported. see #517 
Still you can try `pip install cocotb==1.0.dev3`

**Comment by kimduckhwan** [comment]
Thanks. However, after installing cocotb via `pip install cocotb==1.0.dev3`, I still have same `no module named Simulator` error when I run test_endian_swapper.py
```
[my_env_p2713] [## tests]$ python test_endian_swapper.py
Traceback (most recent call last):
  File "test_endian_swapper.py", line 33, in <module>
    from cocotb.clock import Clock
  File "/home/scratch.duckhwank_gpu/duckhwank_COCOTB/my_env_p2713/lib/python2.7/site-packages/cocotb/clock.py", line 31, in <module>
    import simulator
ImportError: No module named simulator
```

What is the module named simulator?

Thank you

**Comment by themperek** [comment]
No so simple (not yet see #696 )

You need to run 
```
cd cocotb/examples/endian_swapper/tests
make
```

**Comment by jpcf** [comment]
I have the exact same problem
